### PR TITLE
Mois 61 id 004 edit house information

### PR DESCRIPTION
**Pull request by zlatax**
Feature to edit household information from the dropdown menu next to the household name on the household page.

- Similar to creating household: name is required, description is optional.
- Only owner can edit household information
- upload house photo for icon (maybe also as bg img for house page)

Tests are also added to 02_household.cy.ts

### CODE REVIEW

**Review by lolupp — APPROVED** [review]
LGTM

**Comment by geordanbennie** [comment]
My image upload didn't work on preview deployment?

**Comment by zlatax** [comment]
> My image upload didn't work on preview deployment?

Good pick, just fixed it now, should work

**Review by geordanbennie — APPROVED** [review]
Looks good with the image upload

**Pull request merged**
