### PR TITLE
Mois 44 GitHub actions

### PR DESCRIPTION
**Pull request by zlatax**
Set up and configured Cypress for NextJS.
GitHub Actions also set for cypress with a sample test testing firebase access and writes already committed to main.
After this PR, we are able to write E2E, component tests using Cypress.

### CODE REVIEW

**Comment by zlatax** [comment]
Thanks for the review, yup did see it on the way and now that you mention it, makes sense to implement it so will do so!

**Comment by zlatax** [comment]
cypress-firebase library causing too many problems, tests can be written without the ability to bypass Firebase authentication.

**Review by IkePureza — APPROVED** [review]
LGTM, yeah don't think we need the firebase-cypress library as of now.

**Review by edsonli1999 — APPROVED** [review]
LGTM GJ Homi <3

**Pull request merged**
